import { MainLayout } from '@/Layouts/MainLayout'
import { NextPage } from 'next'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <>
      <MainLayout title="Home">
        <h1 className="title">Welcome to random jokes generator!</h1>
        <div className="instructions-container">
          <h2 className="instruction-title">Simple usage instruction:</h2>
          <h3 className="instruction">
            1) Press the button to see a list of jokes
          </h3>
          <h3 className="instruction">2) Press and hold the joke you like</h3>
          <h3 className="instruction">
            3) Enjoy the image generated by AI illustrating the joke
          </h3>
        </div>
        <Link className="link" href={'/jokes'}>
          Go to jokes ⇒
        </Link>
      </MainLayout>
    </>
  )
}

export default Home
